name: Build v2rayNG APK

on:
  workflow_dispatch:
    inputs:
      v2_version:
        description: 'v2rayNG version'
        required: true

      xray_version:
        description: 'xray version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Setup Android environment
        uses: android-actions/setup-android@v2

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'android_keystore.jks'
          fileDir: '/home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/keystore/'
          encodedString: ${{ secrets.SIGNING_KEY }}

      - name: Build v2rayNG APK
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          cd ${{ github.workspace }}/V2rayNG
          chmod 777 *
          cd app/libs
          rm -f libv2ray.aar
          wget -O libv2ray.aar https://github.com/OxJ4ck/AndroidLibXrayLite/releases/download/release/libv2ray.aar
          cd ../..
          sed -i 's/org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8/org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8/' ${{ github.workspace }}/V2rayNG/gradle.properties
          ./gradlew :app:assembleRelease -x test

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: APKs
          path: /home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/build/outputs/apk/release/*.apk

      - name: Upload apk to release
        uses: softprops/action-gh-release@v1
        with:
          name: v2rayNG_${{ github.event.inputs.v2_version }}_${{ github.event.inputs.xray_version }}
          tag_name: v${{ github.event.inputs.v2_version }}_${{ github.event.inputs.xray_version }}
          files: /home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/build/outputs/apk/release/*.apk
